### ISSUE TITLE
Za dużo klasyfikatorów

### ISSUE THREAD

**Issue by kasztanka** [piotermiarer/Sequence-Classification#15]
Narobiło się sporo klasyfikatorów, więc proponuję przenieść je do wspólnego folderu.

Czy ktoś ma jakąś opinię, co do tego czy abstrakcyjna klasa SequenceClassifier powinna też tam być?

**Comment by piotermiarer** [comment]
Dałbym tę klasę razem ze zwykłymi klasyfikatorami. Umieszczenie jej w folderze wyżej utrudniłoby importowanie jej.
