### ISSUE TITLE
Seq learn

### ISSUE THREAD

**Issue by piotermiarer** [piotermiarer/Sequence-Classification#28]
Dodać seqlearn do requierements

**Comment by grzegorzsz18** [comment]
seqlearn jest już w requierements, jak Ci nie działa to usuń obraz dockera i odpal jeszcze raz bo może nie przebudowałeś obrazu po zmianie pliku
docker image rm -f sequences
docker-compose up

**Comment by piotermiarer** [comment]
Nie zauważyłem, że jest, ale patrzyłem tam!
Ślepy jestem...
