### ISSUE TITLE
Iterowanie po zbiorach danych w przepływie

### ISSUE THREAD

**Issue by kasztanka** [piotermiarer/Sequence-Classification#30]
Dobrze by byłoby to dodać do przepływu jakoś, bo dzięki temu łatwiej będzie zaimplementować testy statystyczne (#22 ) i może łatwiej będzie nam samym używać tych zbiorów danych

**Comment by piotermiarer** [comment]
Analogicznie jak dodawanie klasyfikatorów: `comparator.addDataset(...)`

**Comment by piotermiarer** [comment]
Przy okazji można usunąć dzielenie na test i train, bo i tak to jest robione w comparatorze w każdej rundzie.
