### ISSUE TITLE
Valley_data - znaczenie zbioru

### ISSUE THREAD

**Issue by StanislawSzataniak** [piotermiarer/Sequence-Classification#58]
Wybaczcie, że zaśmiecam wasz projekt tymi wiadomościami, jednak pozwolę sobie przekopiować zawartość komentarza pod jednym commitem, bardzo zależy nam na waszej odpowiedzi :)

Cześć,
mam nadzieję że dostrzeżecie tę wiadomość. Razem z grupą znajomych pracujemy nad inżynierką, która tematem nie odbiega znacznie od problemu którym się tu zajmowaliście. Niestety brakuje nam odpowiednich data setów. Jeden ze zbiorów których użyliście, mianowicie ten o nazwie Valley, zwrócił naszą uwagę. Chcielibyśmy użyć go do naszej pracy, jednak nie mamy pojęcia o jego pochodzeniu i znaczeniu zawartych w nim danych. Czy zechcielibyście wspomóc nas w tej sprawie i udzielić odpowiedzi na te pytania?
Pozdrawiam

**Comment by pmiara** [comment]
Hej,

poniżej wklejam opis tego zbioru danych z naszej pracy:


Wzgórza – zbiór współrzędnych określających wysokości geograficzne punktów, zaczerpnięty
z serwisu Machine Learning Repository, autorstwa Leego Grahama [58]. Jest on wykorzysty-
wany do określania, czy podany obszar jest doliną czy wzniesieniem. Składa się on z 2424
przykładów. Dane zostały przekształcone z postaci liczbowej (wysokość punktu) do postaci
symbolicznej określającej stopień zmiany wysokości (mały spadek, średni spadek, duży spa-
dek, mały wzrost, średni wzrost, duży wzrost). Przedmiotem klasyfikacji jest to, czy dany
przykład jest doliną, czy wzgórzem.

Bibliografia:
[58] Lee Graham. UCI Machine Learning Repository, Hill-Valley Data Set, 2008.

**Comment by StanislawSzataniak** [comment]
Wielkie dzięki!
